services:
  # React App served via Nginx — DEV environment
  itt-app:
    image: ghcr.io/khalilksa33/itt.sa-dev:latest
    build: .
    container_name: insight-travel-app-dev
    ports:
      - "8095:80"
    restart: always
    depends_on:
      - itt-backend

  # Express Backend with MongoDB Integration — DEV environment
  itt-backend:
    image: node:18-alpine
    container_name: insight-travel-backend-dev
    working_dir: /app
    volumes:
      - ./server:/app
      - ./uploaded-files:/app/uploaded-files
      - ./uploaded-files:/uploaded-files

    command: sh -c "npm install && npm start"
    ports:
      - "5001:5000"
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/itt_sa_dev
      - STAFF_PASSWORD=admin123

  # MongoDB database — DEV environment
  mongodb:
    image: mongo:6.0
    container_name: insight-travel-db-dev
    volumes:
      - mongo-data-dev:/data/db
    restart: always

volumes:
  mongo-data-dev:
