services:
  # React App served via Nginx
  itt-app:
    image: khalilksa33/itt.sa:latest
    build: .
    container_name: insight-travel-app
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - itt-backend

  # Express Backend with MongoDB Integration
  itt-backend:
    image: node:18-alpine
    container_name: insight-travel-backend
    working_dir: /app
    volumes:
      - ./server:/app
      - ./uploaded-files:/app/uploaded-files
      - ./uploaded-files:/uploaded-files

    command: sh -c "npm install && npm start"
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/itt_sa
      - STAFF_PASSWORD=admin123

  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: insight-travel-db
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:

